// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpepaqzbzbftcydazpxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwZXBhcXpiemJmdGN5ZGF6cHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MTQxMzMsImV4cCI6MjA1NTI5MDEzM30.c4hATnzEPCJgxurHBhOea2GC31qAV-cY5beN0Jkhc-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);